package it.sintegra.badge.business.dao.mybatis.mapper;

import it.sintegra.badge.business.entity.CalendarEvent;
import it.sintegra.badge.business.entity.CalendarEventExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CalendarEventMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mys_calendar_event
     *
     * @mbggenerated Wed Giu 22 16:15:50 CEST 2016
     */
    int countByExample(CalendarEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mys_calendar_event
     *
     * @mbggenerated Wed Giu 22 16:15:50 CEST 2016
     */
    int deleteByExample(CalendarEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mys_calendar_event
     *
     * @mbggenerated Wed Giu 22 16:15:50 CEST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mys_calendar_event
     *
     * @mbggenerated Wed Giu 22 16:15:50 CEST 2016
     */
    int insert(CalendarEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mys_calendar_event
     *
     * @mbggenerated Wed Giu 22 16:15:50 CEST 2016
     */
    int insertSelective(CalendarEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mys_calendar_event
     *
     * @mbggenerated Wed Giu 22 16:15:50 CEST 2016
     */
    List<CalendarEvent> selectByExample(CalendarEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mys_calendar_event
     *
     * @mbggenerated Wed Giu 22 16:15:50 CEST 2016
     */
    CalendarEvent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mys_calendar_event
     *
     * @mbggenerated Wed Giu 22 16:15:50 CEST 2016
     */
    int updateByExampleSelective(@Param("record") CalendarEvent record, @Param("example") CalendarEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mys_calendar_event
     *
     * @mbggenerated Wed Giu 22 16:15:50 CEST 2016
     */
    int updateByExample(@Param("record") CalendarEvent record, @Param("example") CalendarEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mys_calendar_event
     *
     * @mbggenerated Wed Giu 22 16:15:50 CEST 2016
     */
    int updateByPrimaryKeySelective(CalendarEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mys_calendar_event
     *
     * @mbggenerated Wed Giu 22 16:15:50 CEST 2016
     */
    int updateByPrimaryKey(CalendarEvent record);
}