package it.sintegra.badge.business.dao.mybatis.mapper;

import it.sintegra.badge.business.entity.User;
import it.sintegra.badge.business.entity.UserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mys_user
     *
     * @mbggenerated Wed Giu 15 15:19:27 CEST 2016
     */
    int countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mys_user
     *
     * @mbggenerated Wed Giu 15 15:19:27 CEST 2016
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mys_user
     *
     * @mbggenerated Wed Giu 15 15:19:27 CEST 2016
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mys_user
     *
     * @mbggenerated Wed Giu 15 15:19:27 CEST 2016
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mys_user
     *
     * @mbggenerated Wed Giu 15 15:19:27 CEST 2016
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mys_user
     *
     * @mbggenerated Wed Giu 15 15:19:27 CEST 2016
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mys_user
     *
     * @mbggenerated Wed Giu 15 15:19:27 CEST 2016
     */
    User selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mys_user
     *
     * @mbggenerated Wed Giu 15 15:19:27 CEST 2016
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mys_user
     *
     * @mbggenerated Wed Giu 15 15:19:27 CEST 2016
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mys_user
     *
     * @mbggenerated Wed Giu 15 15:19:27 CEST 2016
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mys_user
     *
     * @mbggenerated Wed Giu 15 15:19:27 CEST 2016
     */
    int updateByPrimaryKey(User record);
}