package it.sintegra.badge.business.entity;

import java.util.Date;

public class CalendarEvent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mys_calendar_event.id
     *
     * @mbggenerated Wed Giu 22 16:15:50 CEST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mys_calendar_event.userId
     *
     * @mbggenerated Wed Giu 22 16:15:50 CEST 2016
     */
    private Short userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mys_calendar_event.title
     *
     * @mbggenerated Wed Giu 22 16:15:50 CEST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mys_calendar_event.category
     *
     * @mbggenerated Wed Giu 22 16:15:50 CEST 2016
     */
    private Byte category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mys_calendar_event.start
     *
     * @mbggenerated Wed Giu 22 16:15:50 CEST 2016
     */
    private Date start;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mys_calendar_event.end
     *
     * @mbggenerated Wed Giu 22 16:15:50 CEST 2016
     */
    private Date end;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mys_calendar_event.description
     *
     * @mbggenerated Wed Giu 22 16:15:50 CEST 2016
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mys_calendar_event.id
     *
     * @return the value of mys_calendar_event.id
     *
     * @mbggenerated Wed Giu 22 16:15:50 CEST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mys_calendar_event.id
     *
     * @param id the value for mys_calendar_event.id
     *
     * @mbggenerated Wed Giu 22 16:15:50 CEST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mys_calendar_event.userId
     *
     * @return the value of mys_calendar_event.userId
     *
     * @mbggenerated Wed Giu 22 16:15:50 CEST 2016
     */
    public Short getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mys_calendar_event.userId
     *
     * @param userid the value for mys_calendar_event.userId
     *
     * @mbggenerated Wed Giu 22 16:15:50 CEST 2016
     */
    public void setUserid(Short userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mys_calendar_event.title
     *
     * @return the value of mys_calendar_event.title
     *
     * @mbggenerated Wed Giu 22 16:15:50 CEST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mys_calendar_event.title
     *
     * @param title the value for mys_calendar_event.title
     *
     * @mbggenerated Wed Giu 22 16:15:50 CEST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mys_calendar_event.category
     *
     * @return the value of mys_calendar_event.category
     *
     * @mbggenerated Wed Giu 22 16:15:50 CEST 2016
     */
    public Byte getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mys_calendar_event.category
     *
     * @param category the value for mys_calendar_event.category
     *
     * @mbggenerated Wed Giu 22 16:15:50 CEST 2016
     */
    public void setCategory(Byte category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mys_calendar_event.start
     *
     * @return the value of mys_calendar_event.start
     *
     * @mbggenerated Wed Giu 22 16:15:50 CEST 2016
     */
    public Date getStart() {
        return start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mys_calendar_event.start
     *
     * @param start the value for mys_calendar_event.start
     *
     * @mbggenerated Wed Giu 22 16:15:50 CEST 2016
     */
    public void setStart(Date start) {
        this.start = start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mys_calendar_event.end
     *
     * @return the value of mys_calendar_event.end
     *
     * @mbggenerated Wed Giu 22 16:15:50 CEST 2016
     */
    public Date getEnd() {
        return end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mys_calendar_event.end
     *
     * @param end the value for mys_calendar_event.end
     *
     * @mbggenerated Fri Giu 22 16:15:50 CEST 2016
     */
    public void setEnd(Date end) {
        this.end = end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mys_calendar_event.description
     *
     * @return the value of mys_calendar_event.description
     *
     * @mbggenerated Wed Giu 22 16:15:50 CEST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mys_calendar_event.description
     *
     * @param description the value for mys_calendar_event.description
     *
     * @mbggenerated Wed Giu 22 16:15:50 CEST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}