CREATE TABLE MYS_EVENT_CATEGORY(
	id TINYINT AUTO_INCREMENT PRIMARY KEY,
	label VARCHAR(20) NOT NULL,
	description VARCHAR(255),
	CONSTRAINT MYS_EVENT_CATEGORY_UNIQUE UNIQUE (label)
)ENGINE=INNODB;

CREATE TABLE MYS_USER_PROFILE(
	name VARCHAR(10) NOT NULL,
	description VARCHAR(255),
	CONSTRAINT MYS_USER_PROFILE_UNIQUE UNIQUE (name)
)ENGINE=INNODB;

CREATE TABLE MYS_USER (
	id SMALLINT AUTO_INCREMENT PRIMARY KEY,
	firstname VARCHAR(50) NOT NULL,
	lastname VARCHAR(50) NOT NULL,
	username VARCHAR(20) NOT NULL,
	password VARCHAR(20) NOT NULL,
	profile VARCHAR(10) NOT NULL,
	qualify VARCHAR(50) NOT NULL,
	code SMALLINT,
	CONSTRAINT MYS_USER_USERNAME_UNIQUE UNIQUE (username),
	CONSTRAINT FK_MYS_USER_PROFILE FOREIGN KEY (profile) REFERENCES MYS_USER_PROFILE (name)
)ENGINE=INNODB;

CREATE TABLE MYS_CALENDAR_EVENT(
	id INT AUTO_INCREMENT PRIMARY KEY,
	userId SMALLINT NOT NULL,
	title VARCHAR(70) NOT NULL,
	category TINYINT NOT NULL,
	start DATETIME NOT NULL,
	end DATETIME NOT NULL,
	description VARCHAR(255),
	CONSTRAINT FK_MYS_CAL_EVENT_USER FOREIGN KEY (userId) REFERENCES MYS_USER (id),
	CONSTRAINT FK_MYS_CAL_EVENT_CATEGORY FOREIGN KEY (category) REFERENCES MYS_EVENT_CATEGORY (id)
)ENGINE=INNODB;